eureka:
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/,http://eureka-tertiary:8012/eureka/
  environment: local
  instance:
    hostname: eureka-secondary
    metadataMap:
      zone: Zone1
    preferIpAddress: false
  server:
    eviction-interval-timer-in-ms: 20000
  shouldBatchReplication: true
server:
  port: 8011
spring:
  application:
    name: eureka-server-clustered
  profiles:
    active: secondary
