eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
  instance:
    hostname: eureka-client-instance
operator:
  list: '*,/'
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  profiles:
    active: operator
